# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: pb/packet_head.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import Dict

import betterproto


class DebugNotifyRetcode(betterproto.Enum):
    SUCC = 0
    FAIL = 1


class DebugNotifyEnum(betterproto.Enum):
    ZERO = 0
    CMD_ID = 101
    TARGET_SERVICE = 101
    ENET_CHANNEL_ID = 2
    ENET_IS_RELIABLE = 1


@dataclass
class PacketHead(betterproto.Message):
    packet_id: int = betterproto.uint32_field(1)
    rpc_id: int = betterproto.uint32_field(2)
    client_sequence_id: int = betterproto.uint32_field(3)
    enet_channel_id: int = betterproto.uint32_field(4)
    enet_is_reliable: int = betterproto.uint32_field(5)
    user_id: int = betterproto.uint32_field(11)
    user_ip: int = betterproto.uint32_field(12)
    user_session_id: int = betterproto.uint32_field(13)
    recv_time_ms: int = betterproto.uint64_field(21)
    rpc_begin_time_ms: int = betterproto.uint32_field(22)
    ext_map: Dict[int, int] = betterproto.map_field(
        23, betterproto.TYPE_UINT32, betterproto.TYPE_UINT32
    )
    sender_app_id: int = betterproto.uint32_field(24)
    source_service: int = betterproto.uint32_field(31)
    target_service: int = betterproto.uint32_field(32)
    service_app_id_map: Dict[int, int] = betterproto.map_field(
        33, betterproto.TYPE_UINT32, betterproto.TYPE_UINT32
    )
    is_set_game_thread: bool = betterproto.bool_field(34)
    game_thread_index: int = betterproto.uint32_field(35)


@dataclass
class DebugNotify(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    name: str = betterproto.string_field(2)
    retcode: "DebugNotifyRetcode" = betterproto.enum_field(3)
